// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLzguX_N7540Ceh_yegYHzj3cQdxwsE-w',
    appId: '1:960958133531:web:6b8c682cb433dea4934fbe',
    messagingSenderId: '960958133531',
    projectId: 'mimi-base',
    authDomain: 'mimi-base.firebaseapp.com',
    storageBucket: 'mimi-base.appspot.com',
    measurementId: 'G-E7E4CL10X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD88NOgTNLOc0UAb1kOvUKSVGasw5DHpLk',
    appId: '1:960958133531:android:ec61ec62ee05a05d934fbe',
    messagingSenderId: '960958133531',
    projectId: 'mimi-base',
    storageBucket: 'mimi-base.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEQGftBvevqIwJjEIIF1PLDlzfY05T9AU',
    appId: '1:960958133531:ios:f876ce61fda5d45e934fbe',
    messagingSenderId: '960958133531',
    projectId: 'mimi-base',
    storageBucket: 'mimi-base.appspot.com',
    iosBundleId: 'com.pricebase.pricebase',
  );
}
