// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL8akpHPjRLxWd0z8tvvwStQvli82NEUk',
    appId: '1:546515599662:web:27bb679641b25ddca13abf',
    messagingSenderId: '546515599662',
    projectId: 'price-base-1d428',
    authDomain: 'price-base-1d428.firebaseapp.com',
    storageBucket: 'price-base-1d428.appspot.com',
    measurementId: 'G-162K65GL03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIYsRIxDIgIw4mjiRXvgv3g_iktY2IQ7I',
    appId: '1:546515599662:android:5a234f59a2c01f86a13abf',
    messagingSenderId: '546515599662',
    projectId: 'price-base-1d428',
    storageBucket: 'price-base-1d428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd2BYokz8ypmyVc4nIMyulqLsYcIhI8Po',
    appId: '1:546515599662:ios:9f4b6cd7a7ed9641a13abf',
    messagingSenderId: '546515599662',
    projectId: 'price-base-1d428',
    storageBucket: 'price-base-1d428.appspot.com',
    iosBundleId: 'com.example.test',
  );
}
